// Generated by Cursor AI and reviewed by Victor Jason-Nwachukwu

// ============================================
// ASA Policy App - Admin Panel JavaScript
// ============================================

// Storage Keys
const STORAGE_KEYS = {
    POLICIES: 'asa_policies',
    BYLAWS: 'asa_bylaws',
    SUGGESTIONS: 'asa_suggestions',
    ADMIN_USER: 'asa_admin_user',
    ADMIN_MEMBERS: 'asa_admin_members',
    SESSION: 'asa_session',
    REVIEWS: 'asa_policy_reviews',
    CURRENT_USER: 'asa_current_user'
};

// Initialize on page load
document.addEventListener('DOMContentLoaded', async function() {
    // Only initialize sample data if API is not available (fallback)
    if (typeof asaAPI === 'undefined') {
        console.warn('API not loaded, using localStorage fallback');
        initializeSampleData();
    }
    await initializePage();
});

// ============================================
// Sample Data Initialization (for demo)
// ============================================

function initializeSampleData() {
    // Get existing policies or initialize empty array
    const existingPolicies = getPolicies();
    const existingPolicyIds = new Set(existingPolicies.map(p => p.policyId || p.id));
    
    // Sample policies - All ASA Policies
    const samplePolicies = [
        // Section 1
        {
            id: 'policy_1_1_1',
            policyId: '1.1.1',
            name: 'Vision Statement',
            policyName: 'Vision Statement',
            type: 'vision',
            policyType: 'vision',
            section: '1',
            content: 'Through leadership and responsibility, the Augustana Students\' Association serves, represents, and defends in the best interest of students.',
            policyContent: 'Through leadership and responsibility, the Augustana Students\' Association serves, represents, and defends in the best interest of students.',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_1_1_2',
            policyId: '1.1.2',
            name: 'Mission Statement',
            policyName: 'Mission Statement',
            type: 'policy',
            policyType: 'policy',
            section: '1',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_1_1_3',
            policyId: '1.1.3',
            name: 'Code of Conduct',
            policyName: 'Code of Conduct',
            type: 'code',
            policyType: 'code',
            section: '1',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        // Section 2
        {
            id: 'policy_2_1_0',
            policyId: '2.1.0',
            name: 'Policy Making',
            policyName: 'Policy Making',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_2_1',
            policyId: '2.2.1',
            name: 'Type of Board',
            policyName: 'Type of Board',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_2_2',
            policyId: '2.2.2',
            name: 'Board Structure',
            policyName: 'Board Structure',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_3_1',
            policyId: '2.3.1',
            name: 'Proxy Voting',
            policyName: 'Proxy Voting',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_3_2',
            policyId: '2.3.2',
            name: 'Board Committees',
            policyName: 'Board Committees',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_3_3',
            policyId: '2.3.3',
            name: 'Officers',
            policyName: 'Officers',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_3_4',
            policyId: '2.3.4',
            name: 'Executive Members',
            policyName: 'Executive Members',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_3_5',
            policyId: '2.3.5',
            name: 'Membership',
            policyName: 'Membership',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_3_6',
            policyId: '2.3.6',
            name: 'Council Member Job Description',
            policyName: 'Council Member Job Description',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_3_7',
            policyId: '2.3.7',
            name: 'External Representation',
            policyName: 'External Representation',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_3_8',
            policyId: '2.3.8',
            name: 'Faculty Liaison',
            policyName: 'Faculty Liaison',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_3_9',
            policyId: '2.3.9',
            name: 'Transition Training',
            policyName: 'Transition Training',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_3_10',
            policyId: '2.3.10',
            name: 'Annual Evaluations',
            policyName: 'Annual Evaluations',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_3_11',
            policyId: '2.3.11',
            name: 'Report Requirements',
            policyName: 'Report Requirements',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_3_12',
            policyId: '2.3.12',
            name: 'External Committee Reporting',
            policyName: 'External Committee Reporting',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_4_1',
            policyId: '2.4.1',
            name: 'CoFA Membership',
            policyName: 'CoFA Membership',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_4_2',
            policyId: '2.4.2',
            name: 'External Organizational Membership',
            policyName: 'External Organizational Membership',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_5_1',
            policyId: '2.5.1',
            name: 'General Election Policy',
            policyName: 'General Election Policy',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_5_2',
            policyId: '2.5.2',
            name: 'Candidate Election Guidelines',
            policyName: 'Candidate Election Guidelines',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_5_3',
            policyId: '2.5.3',
            name: 'Candidate Discipline and Dismissal',
            policyName: 'Candidate Discipline and Dismissal',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_5_4',
            policyId: '2.5.4',
            name: 'Plebiscites & Referenda',
            policyName: 'Plebiscites & Referenda',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_2_5_5',
            policyId: '2.5.5',
            name: 'Appointment to ASC',
            policyName: 'Appointment to ASC',
            type: 'policy',
            policyType: 'policy',
            section: '2',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        // Section 3
        {
            id: 'policy_3_1_1',
            policyId: '3.1.1',
            name: 'Employee Definitions',
            policyName: 'Employee Definitions',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_1_2',
            policyId: '3.1.2',
            name: 'Personnel Administration',
            policyName: 'Personnel Administration',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_1_3',
            policyId: '3.1.3',
            name: 'Hiring Practices',
            policyName: 'Hiring Practices',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_1_4',
            policyId: '3.1.4',
            name: 'Recruitment',
            policyName: 'Recruitment',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_1_5',
            policyId: '3.1.5',
            name: 'Interviewing and Selection',
            policyName: 'Interviewing and Selection',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_1_6',
            policyId: '3.1.6',
            name: 'Orientation and Training',
            policyName: 'Orientation and Training',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_1_7',
            policyId: '3.1.7',
            name: 'Probationary Periods',
            policyName: 'Probationary Periods',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_1_8',
            policyId: '3.1.8',
            name: 'Job Specifications',
            policyName: 'Job Specifications',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_1_9',
            policyId: '3.1.9',
            name: 'Staff Appraisals',
            policyName: 'Staff Appraisals',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_1_10',
            policyId: '3.1.10',
            name: 'Discipline & Dismissal',
            policyName: 'Discipline & Dismissal',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_1_11',
            policyId: '3.1.11',
            name: 'Executive Director Job Description',
            policyName: 'Executive Director Job Description',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_1_12',
            policyId: '3.1.12',
            name: 'Annual Employees Policy',
            policyName: 'Annual Employees Policy',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_1_13',
            policyId: '3.1.13',
            name: 'Sexual Harassment Policy',
            policyName: 'Sexual Harassment Policy',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_2_1',
            policyId: '3.2.1',
            name: 'Travel and Related Expenses',
            policyName: 'Travel and Related Expenses',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_2_2',
            policyId: '3.2.2',
            name: 'Bursary Payment Schedule',
            policyName: 'Bursary Payment Schedule',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_2_3',
            policyId: '3.2.3',
            name: 'Review Engagement',
            policyName: 'Review Engagement',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_2_4',
            policyId: '3.2.4',
            name: 'Budget',
            policyName: 'Budget',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_2_5',
            policyId: '3.2.5',
            name: 'Faculty Association Membership Fee',
            policyName: 'Faculty Association Membership Fee',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_2_6',
            policyId: '3.2.6',
            name: 'Campus Association Transfer Payments',
            policyName: 'Campus Association Transfer Payments',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_3_1',
            policyId: '3.3.1',
            name: 'Student Activities Coordinating Committee',
            policyName: 'Student Activities Coordinating Committee',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_3_2',
            policyId: '3.3.2',
            name: 'Clubs',
            policyName: 'Clubs',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_3_3',
            policyId: '3.3.3',
            name: 'Granting',
            policyName: 'Granting',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_3_4',
            policyId: '3.3.4',
            name: 'Dagligtale Newspaper',
            policyName: 'Dagligtale Newspaper',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_3_5',
            policyId: '3.3.5',
            name: 'ASA Offensive Content Regulations',
            policyName: 'ASA Offensive Content Regulations',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_3_7',
            policyId: '3.3.7',
            name: 'Branding',
            policyName: 'Branding',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_3_8',
            policyId: '3.3.8',
            name: 'Awards',
            policyName: 'Awards',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_3_10',
            policyId: '3.3.10',
            name: 'Students\' Association Retreat',
            policyName: 'Students\' Association Retreat',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_3_12',
            policyId: '3.3.12',
            name: 'Multimedia Screens',
            policyName: 'Multimedia Screens',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_4_1',
            policyId: '3.4.1',
            name: 'Access and Administration',
            policyName: 'Access and Administration',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_4_2',
            policyId: '3.4.2',
            name: 'Rentals',
            policyName: 'Rentals',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_4_3',
            policyId: '3.4.3',
            name: 'Purchasing',
            policyName: 'Purchasing',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_4_4',
            policyId: '3.4.4',
            name: 'Boardroom Booking',
            policyName: 'Boardroom Booking',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_4_5',
            policyId: '3.4.5',
            name: 'Payments',
            policyName: 'Payments',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_4_6',
            policyId: '3.4.6',
            name: 'Equipment Rental',
            policyName: 'Equipment Rental',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'policy_3_4_7',
            policyId: '3.4.7',
            name: 'Safe and Responsible Use of Technology',
            policyName: 'Safe and Responsible Use of Technology',
            type: 'policy',
            policyType: 'policy',
            section: '3',
            content: '',
            policyContent: '',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        }
    ];

    // Sample bylaws
    const sampleBylaws = [
        {
            id: 'bylaw_1',
            number: 1,
            bylawNumber: 1,
            title: 'General Provisions',
            bylawTitle: 'General Provisions',
            content: 'These bylaws govern the operations and procedures of the Augustana Students\' Association.',
            bylawContent: 'These bylaws govern the operations and procedures of the Augustana Students\' Association.',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        },
        {
            id: 'bylaw_2',
            number: 2,
            bylawNumber: 2,
            title: 'Membership Requirements',
            bylawTitle: 'Membership Requirements',
            content: 'All students enrolled at Augustana University are automatically members of the association.',
            bylawContent: 'All students enrolled at Augustana University are automatically members of the association.',
            status: 'approved',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
        }
    ];

    // Sample suggestions
    const sampleSuggestions = [
        {
            id: 'suggestion_1',
            policyReference: 'Section 1.1.1',
            content: 'I suggest we add more transparency to the decision-making process.',
            suggestion: 'I suggest we add more transparency to the decision-making process.',
            viewed: false,
            createdAt: new Date(Date.now() - 86400000).toISOString()
        },
        {
            id: 'suggestion_2',
            policyReference: 'Section 2',
            content: 'Could we have more frequent town hall meetings?',
            suggestion: 'Could we have more frequent town hall meetings?',
            viewed: true,
            createdAt: new Date(Date.now() - 172800000).toISOString()
        }
    ];

    // Merge sample policies with existing ones (only add if policyId doesn't exist)
    const policiesToAdd = samplePolicies.filter(p => !existingPolicyIds.has(p.policyId));
    const mergedPolicies = [...existingPolicies, ...policiesToAdd];
    
    // Always ensure all standard policies exist - replace if missing or add new ones
    // This ensures the complete policy list is always available
    const allPolicyIds = new Set(samplePolicies.map(p => p.policyId));
    const finalPolicies = [];
    
    // Keep existing policies that match standard policyIds, but update them with standard data
    samplePolicies.forEach(stdPolicy => {
        const existingIndex = existingPolicies.findIndex(p => p.policyId === stdPolicy.policyId);
        if (existingIndex !== -1) {
            // Keep existing but ensure it has all standard fields
            finalPolicies.push({ ...stdPolicy, ...existingPolicies[existingIndex] });
        } else {
            // Add new standard policy
            finalPolicies.push(stdPolicy);
        }
    });
    
    // Add any custom policies that don't match standard IDs
    existingPolicies.forEach(p => {
        if (!allPolicyIds.has(p.policyId)) {
            finalPolicies.push(p);
        }
    });
    
    // Get existing bylaws and suggestions
    const existingBylaws = getBylaws();
    const existingSuggestions = getSuggestions();
    
    // Always save to ensure all policies are present
    savePolicies(finalPolicies);
    
    // Only initialize bylaws and suggestions if storage is empty
    if (existingBylaws.length === 0) {
        saveBylaws(sampleBylaws);
    }
    if (existingSuggestions.length === 0) {
        saveSuggestions(sampleSuggestions);
    }
}

// ============================================
// Page Initialization
// ============================================

function initializePage() {
    const currentPage = getCurrentPage();
    
    // Check authentication for admin pages (except login)
    if (currentPage !== 'login' && !isAuthenticated()) {
        redirectToLogin();
        return;
    }

    // Initialize page-specific functionality
    switch(currentPage) {
        case 'login':
            initLoginPage();
            break;
        case 'dashboard':
            initDashboard();
            break;
        case 'policies':
            initPoliciesPage();
            break;
        case 'policy-form':
            initPolicyForm();
            break;
        case 'bylaw':
            initBylawsPage();
            break;
        case 'bylaw-form':
            initBylawForm();
            break;
        case 'approvals':
            // Approvals page has its own initialization in the HTML
            break;
        case 'suggestions-manage':
            initSuggestionsPage();
            break;
    }

    // Initialize common functionality
    initSearch();
    initSidebarNavigation();
}

function getCurrentPage() {
    const path = window.location.pathname;
    const filename = path.split('/').pop() || 'index.html';
    
    if (filename.includes('login')) return 'login';
    if (filename.includes('dashboard')) return 'dashboard';
    if (filename.includes('policy-view')) return 'policy-view';
    if (filename.includes('policy-form')) return 'policy-form';
    if (filename.includes('policies')) return 'policies';
    if (filename.includes('bylaw-view')) return 'bylaw-view';
    if (filename.includes('bylaw-form')) return 'bylaw-form';
    if (filename.includes('bylaw')) return 'bylaw';
    if (filename.includes('approvals')) return 'approvals';
    if (filename.includes('suggestions')) return 'suggestions-manage';
    
    return 'dashboard';
}

// ============================================
// Authentication
// ============================================

function isAuthenticated() {
    const session = localStorage.getItem(STORAGE_KEYS.SESSION);
    return session === 'true';
}

function setAuthenticated(value) {
    localStorage.setItem(STORAGE_KEYS.SESSION, value ? 'true' : 'false');
}

function redirectToLogin() {
    window.location.href = 'login.html';
}

function logout() {
    setAuthenticated(false);
    localStorage.removeItem('asa_current_admin');
    redirectToLogin();
}

// ============================================
// Profile Panel
// ============================================

function toggleProfilePanel() {
    const panel = document.getElementById('profilePanel');
    if (panel) {
        panel.classList.toggle('hidden');
        if (!panel.classList.contains('hidden')) {
            loadProfileData();
        }
    }
}

function closeProfilePanel() {
    const panel = document.getElementById('profilePanel');
    if (panel) {
        panel.classList.add('hidden');
    }
}

async function loadProfileData() {
    try {
        let currentAdmin = null;
        
        // Try to get from API first
        if (typeof asaAPI !== 'undefined' && asaAPI.isAuthenticated()) {
            try {
                const user = await asaAPI.auth.getCurrentUser();
                if (user) {
                    // Parse name field if it exists (format: "FirstName LastName" or just stored separately)
                    const nameParts = user.name ? user.name.split(' ') : [];
                    currentAdmin = {
                        id: user.id,
                        email: user.email,
                        firstName: user.firstName || nameParts[0] || '',
                        lastName: user.lastName || nameParts.slice(1).join(' ') || '',
                        name: user.name || ''
                    };
                }
            } catch (e) {
                console.warn('Could not fetch user from API, using localStorage:', e);
            }
        }
        
        // Fallback to localStorage
        if (!currentAdmin) {
            const currentAdminStr = localStorage.getItem('asa_current_admin');
            if (currentAdminStr) {
                currentAdmin = JSON.parse(currentAdminStr);
            }
        }
        
        if (!currentAdmin) {
            console.warn('No current admin found');
            return;
        }
        
        // Update profile fields - make firstName and lastName editable
        const firstNameEl = document.getElementById('profileFirstName');
        const lastNameEl = document.getElementById('profileLastName');
        const emailEl = document.getElementById('profileEmail');
        
        // Convert firstName and lastName to editable inputs
        if (firstNameEl && !firstNameEl.querySelector('input')) {
            const firstNameValue = currentAdmin.firstName || '';
            firstNameEl.innerHTML = `<input type="text" class="profile-input" id="profileFirstNameInput" value="${firstNameValue}" placeholder="Enter first name">`;
            setupProfileInput('profileFirstNameInput', 'firstName');
        }
        
        if (lastNameEl && !lastNameEl.querySelector('input')) {
            const lastNameValue = currentAdmin.lastName || '';
            lastNameEl.innerHTML = `<input type="text" class="profile-input" id="profileLastNameInput" value="${lastNameValue}" placeholder="Enter last name">`;
            setupProfileInput('profileLastNameInput', 'lastName');
        }
        
        if (emailEl) {
            emailEl.textContent = currentAdmin.email || '-';
        }
        
        // Update stored admin data
        localStorage.setItem('asa_current_admin', JSON.stringify(currentAdmin));
    } catch (e) {
        console.error('Error loading profile data:', e);
    }
}

// Setup auto-save for profile input fields
function setupProfileInput(inputId, fieldName) {
    const input = document.getElementById(inputId);
    if (!input) return;
    
    let saveTimeout = null;
    
    input.addEventListener('input', function() {
        // Clear previous timeout
        if (saveTimeout) {
            clearTimeout(saveTimeout);
        }
        
        // Show saving indicator
        const savingIndicator = input.parentElement.querySelector('.saving-indicator');
        if (savingIndicator) {
            savingIndicator.textContent = 'Saving...';
            savingIndicator.style.display = 'inline';
        }
        
        // Auto-save after 1 second of no typing
        saveTimeout = setTimeout(async () => {
            await saveProfileField(fieldName, input.value);
            
            // Update saving indicator
            const savingIndicator = input.parentElement.querySelector('.saving-indicator');
            if (savingIndicator) {
                savingIndicator.textContent = 'Saved ✓';
                savingIndicator.style.display = 'inline';
                setTimeout(() => {
                    savingIndicator.style.display = 'none';
                }, 2000);
            }
        }, 1000);
    });
    
    // Add saving indicator
    if (!input.parentElement.querySelector('.saving-indicator')) {
        const indicator = document.createElement('span');
        indicator.className = 'saving-indicator';
        indicator.style.display = 'none';
        indicator.style.marginLeft = '8px';
        indicator.style.fontSize = '12px';
        indicator.style.color = '#28a745';
        input.parentElement.appendChild(indicator);
    }
}

// Save profile field to API and localStorage
async function saveProfileField(fieldName, value) {
    try {
        // Get current admin data
        const currentAdminStr = localStorage.getItem('asa_current_admin');
        let currentAdmin = currentAdminStr ? JSON.parse(currentAdminStr) : {};
        
        // Update the field
        currentAdmin[fieldName] = value;
        
        // Update localStorage immediately
        localStorage.setItem('asa_current_admin', JSON.stringify(currentAdmin));
        
        // Try to update via API if available
        if (typeof asaAPI !== 'undefined' && asaAPI.isAuthenticated()) {
            try {
                // Combine firstName and lastName into name field for API
                const name = [currentAdmin.firstName || '', currentAdmin.lastName || '']
                    .filter(n => n.trim())
                    .join(' ')
                    .trim();
                
                await asaAPI.auth.updateProfile({ name: name || null });
            } catch (apiError) {
                console.warn('Could not update profile via API, saved locally:', apiError);
            }
        }
    } catch (error) {
        console.error('Error saving profile field:', error);
    }
}

function handleLogout() {
    if (confirm('Are you sure you want to logout?')) {
        logout();
    }
}

// ============================================
// Login Page
// ============================================

function initLoginPage() {
    const loginForm = document.getElementById('loginForm');
    if (loginForm) {
        loginForm.addEventListener('submit', handleLogin);
    }

    // Authentication now uses backend API
}

async function handleLogin(e) {
    e.preventDefault();
    
    const email = document.getElementById('email').value.trim().toLowerCase();
    const password = document.getElementById('password').value;

    // Simple validation
    if (!email || !password) {
        alert('Please enter both email and password');
        return;
    }

    try {
        // Login via API
        const loginResponse = await asaAPI.auth.login(email, password);
        
        // Login successful - token is stored in api.js
        setAuthenticated(true);
        
        // Store user info for display
        localStorage.setItem('asa_current_admin', JSON.stringify(loginResponse.user));
        
        // Redirect to dashboard
        window.location.href = 'dashboard.html';
    } catch (error) {
        console.error('Login error:', error);
        alert(error.message || 'Invalid email or password. Please check your credentials.');
    }
}

// ============================================
// Dashboard
// ============================================

async function initDashboard() {
    await updateDashboardStats();
}

async function updateDashboardStats() {
    try {
        const policies = await getPolicies();
        const bylaws = await getBylaws();
        const suggestions = await getSuggestions();

        const pendingPolicies = policies.filter(p => p.status === 'pending').length;
        const newSuggestions = suggestions.filter(s => s.status === 'pending').length;

        document.getElementById('totalPolicies').textContent = policies.length;
        document.getElementById('pendingApproval').textContent = pendingPolicies;
        document.getElementById('totalBylaws').textContent = bylaws.length;
        document.getElementById('newSuggestions').textContent = newSuggestions;
    } catch (error) {
        console.error('Error updating dashboard stats:', error);
    }
}

// ============================================
// Policies Management
// ============================================

async function initPoliciesPage() {
    await loadPolicies();
}

async function getPolicies(filters = {}) {
    if (typeof asaAPI === 'undefined') {
        // Fallback to localStorage if API not available
        const stored = localStorage.getItem(STORAGE_KEYS.POLICIES);
        return stored ? JSON.parse(stored) : [];
    }
    
    try {
        const policies = await asaAPI.policies.getAllPolicies(filters);
        // Normalize API response to match expected format
        return policies.map(p => ({
            id: p.id,
            policyId: p.policy_id || p.id,
            name: p.policy_name || p.name || 'Untitled',
            policyName: p.policy_name || p.name || 'Untitled',
            content: p.policy_content || p.content || '',
            policyContent: p.policy_content || p.content || '',
            section: p.section || '1',
            status: p.status || 'draft',
            updatedAt: p.updated_at || p.created_at,
            createdAt: p.created_at
        }));
    } catch (error) {
        console.error('Error fetching policies:', error);
        return [];
    }
}

// Get section name from section number
function getSectionName(section) {
    const sectionNames = {
        '1': 'Organizational Identity & Values',
        '2': 'Governance & Elections',
        '3': 'Operations, Staff & Finance'
    };
    return sectionNames[section] || `Section ${section}`;
}

function savePolicies(policies) {
    localStorage.setItem(STORAGE_KEYS.POLICIES, JSON.stringify(policies));
}

async function loadPolicies() {
    const container = document.getElementById('policiesList');
    if (!container) return;
    
    container.innerHTML = '<div class="loading">Loading policies...</div>';
    
    try {
        const policies = await getPolicies();

        if (policies.length === 0) {
        container.innerHTML = `
            <div class="empty-state">
                <div class="empty-state-icon">📄</div>
                <div class="empty-state-text">No policies found</div>
                <div class="empty-state-subtext">Create your first policy to get started</div>
            </div>
        `;
        return;
    }

    // Group policies by section
    const grouped = groupPoliciesBySection(policies);
    
    let html = '';
    for (const [section, sectionPolicies] of Object.entries(grouped)) {
        const sectionName = getSectionName(section);
        html += `
            <div class="policy-section expanded" data-section="${section}">
                <div class="policy-section-header" onclick="toggleSection('${section}')">
                    <span class="policy-section-title">${sectionName}</span>
                    <span class="policy-section-toggle">▼</span>
                </div>
                <div class="policy-items">
                    ${sectionPolicies.map(policy => renderPolicyItem(policy)).join('')}
                </div>
            </div>
        `;
    }

        container.innerHTML = html;
    } catch (error) {
        console.error('Error loading policies:', error);
        container.innerHTML = `
            <div class="empty-state">
                <div class="empty-state-icon">⚠️</div>
                <div class="empty-state-text">Error loading policies</div>
                <div class="empty-state-subtext">${error.message || 'Please try again later'}</div>
            </div>
        `;
    }
}

function groupPoliciesBySection(policies) {
    const grouped = {};
    policies.forEach(policy => {
        const section = policy.section || '1';
        if (!grouped[section]) {
            grouped[section] = [];
        }
        grouped[section].push(policy);
    });
    return grouped;
}

function renderPolicyItem(policy) {
    const statusClass = policy.status || 'draft';
    const statusText = (policy.status || 'draft').charAt(0).toUpperCase() + (policy.status || 'draft').slice(1);
    
    return `
        <div class="policy-item" data-id="${policy.id}">
            <div class="policy-item-header">
                <div class="policy-item-title">${policy.name || policy.policyName || 'Untitled Policy'}</div>
                <div class="policy-item-actions">
                    <button class="action-btn view" onclick="viewPolicy('${policy.id}')" title="View">👁️</button>
                    <button class="action-btn edit" onclick="editPolicy('${policy.id}')" title="Edit">✏️</button>
                    <button class="action-btn delete" onclick="deletePolicy('${policy.id}')" title="Delete">🗑️</button>
                </div>
            </div>
            <div class="policy-item-meta">
                <div>ID: ${policy.policyId || policy.id}</div>
                <div class="policy-status ${statusClass}">${statusText}</div>
            </div>
        </div>
    `;
}

function toggleSection(section) {
    const sectionEl = document.querySelector(`[data-section="${section}"]`);
    if (sectionEl) {
        sectionEl.classList.toggle('expanded');
    }
}

function viewPolicy(id) {
    window.location.href = `policy-view.html?id=${id}`;
}

function editPolicy(id) {
    window.location.href = `policy-form.html?id=${id}`;
}

async function deletePolicy(id) {
    try {
        // Get policy info first (try API, fallback to localStorage)
        let policy = null;
        if (typeof asaAPI !== 'undefined') {
            try {
                policy = await asaAPI.policies.getPolicy(id);
            } catch (e) {
                // If API fails, try localStorage
                const policies = await getPoliciesSync();
                policy = policies.find(p => p.id === id);
            }
        } else {
            const policies = await getPoliciesSync();
            policy = policies.find(p => p.id === id);
        }
        
        const policyName = policy ? (policy.policy_name || policy.name || policy.policyName || 'this policy') : 'this policy';
        
        if (confirm(`⚠️ WARNING: Are you sure you want to delete "${policyName}"?\n\nThis action cannot be undone. The policy will be permanently removed from the system.`)) {
            if (typeof asaAPI !== 'undefined') {
                // Use API
                await asaAPI.policies.deletePolicy(id);
            } else {
                // Fallback to localStorage
                const policies = await getPoliciesSync();
                const filtered = policies.filter(p => p.id !== id);
                savePolicies(filtered);
            }
            await loadPolicies();
            alert('Policy deleted successfully.');
        }
    } catch (error) {
        console.error('Error deleting policy:', error);
        alert('Error deleting policy: ' + (error.message || 'Unknown error'));
    }
}

// ============================================
// Policy Form
// ============================================

async function initPolicyForm() {
    const form = document.getElementById('policyForm');
    const urlParams = new URLSearchParams(window.location.search);
    const policyId = urlParams.get('id');

    if (policyId) {
        await loadPolicyForEdit(policyId);
    }

    if (form) {
        form.addEventListener('submit', handlePolicySubmit);
    }
}

async function loadPolicyForEdit(id) {
    try {
        let policy = null;
        if (typeof asaAPI !== 'undefined') {
            const policyData = await asaAPI.policies.getPolicy(id);
            // Normalize API response
            policy = {
                id: policyData.id,
                policyId: policyData.policy_id || policyData.id,
                name: policyData.policy_name || policyData.name || 'Untitled',
                policyName: policyData.policy_name || policyData.name || 'Untitled',
                content: policyData.policy_content || policyData.content || '',
                policyContent: policyData.policy_content || policyData.content || '',
                section: policyData.section || '1',
                status: policyData.status || 'draft'
            };
        } else {
            const policies = await getPoliciesSync();
            policy = policies.find(p => p.id === id);
        }
        
        if (policy) {
        document.getElementById('formTitle').textContent = 'Update Policy';
        document.getElementById('policyId').value = policy.policyId || '';
        document.getElementById('policyName').value = policy.name || policy.policyName || '';
        document.getElementById('section').value = policy.section || '';
        document.getElementById('policyContent').value = policy.content || policy.policyContent || '';
        
            // Store the ID for update
            document.getElementById('policyForm').dataset.editId = id;
        }
    } catch (error) {
        console.error('Error loading policy for edit:', error);
        alert('Error loading policy: ' + (error.message || 'Unknown error'));
    }
}

async function handlePolicySubmit(e) {
    e.preventDefault();
    
    const form = e.target;
    const editId = form.dataset.editId;
    
    const policyData = {
        policy_id: document.getElementById('policyId').value,
        policy_name: document.getElementById('policyName').value,
        section: document.getElementById('section').value,
        policy_content: document.getElementById('policyContent').value,
        status: 'pending'
    };

    try {
        if (editId && typeof asaAPI !== 'undefined') {
            // Update existing via API
            await asaAPI.policies.updatePolicy(editId, policyData);
        } else if (typeof asaAPI !== 'undefined') {
            // Create new via API
            await asaAPI.policies.createPolicy(policyData);
        } else {
            // Fallback to localStorage
            const policies = await getPoliciesSync();
            const fullPolicyData = {
                id: editId || generateId(),
                policyId: policyData.policy_id,
                name: policyData.policy_name,
                policyName: policyData.policy_name,
                type: 'policy',
                policyType: 'policy',
                section: policyData.section,
                content: policyData.policy_content,
                policyContent: policyData.policy_content,
                status: 'pending',
                createdAt: editId ? policies.find(p => p.id === editId)?.createdAt : new Date().toISOString(),
                updatedAt: new Date().toISOString()
            };
            
            if (editId) {
                const index = policies.findIndex(p => p.id === editId);
                if (index !== -1) {
                    policies[index] = { ...policies[index], ...fullPolicyData };
                }
            } else {
                policies.push(fullPolicyData);
            }
            savePolicies(policies);
        }
        
        alert('Policy submitted for approval successfully!');
        window.location.href = 'policies.html';
    } catch (error) {
        console.error('Error saving policy:', error);
        alert('Error saving policy: ' + (error.message || 'Unknown error'));
    }
}

function generateId() {
    return 'policy_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
}

// ============================================
// Bylaws Management
// ============================================

async function initBylawsPage() {
    await loadBylaws();
}

async function getBylawsSync() {
    // Synchronous version for backward compatibility
    const stored = localStorage.getItem(STORAGE_KEYS.BYLAWS);
    return stored ? JSON.parse(stored) : [];
}

async function getBylaws(filters = {}) {
    if (typeof asaAPI === 'undefined') {
        return await getBylawsSync();
    }
    
    try {
        const bylaws = await asaAPI.bylaws.getAllBylaws(filters);
        // Normalize API response
        return bylaws.map(b => ({
            id: b.id,
            number: b.bylaw_number || b.number || 0,
            bylawNumber: b.bylaw_number || b.number || 0,
            title: b.bylaw_title || b.title || 'Untitled',
            bylawTitle: b.bylaw_title || b.title || 'Untitled',
            content: b.bylaw_content || b.content || '',
            bylawContent: b.bylaw_content || b.content || '',
            status: b.status || 'draft',
            updatedAt: b.updated_at || b.created_at,
            createdAt: b.created_at
        }));
    } catch (error) {
        console.error('Error fetching bylaws:', error);
        return [];
    }
}

function saveBylaws(bylaws) {
    localStorage.setItem(STORAGE_KEYS.BYLAWS, JSON.stringify(bylaws));
}

async function loadBylaws() {
    const container = document.getElementById('bylawsList');
    if (!container) return;
    
    container.innerHTML = '<div class="loading">Loading bylaws...</div>';
    
    try {
        const bylaws = await getBylaws();

        if (bylaws.length === 0) {
        container.innerHTML = `
            <div class="empty-state">
                <div class="empty-state-icon">📋</div>
                <div class="empty-state-text">No bylaws found</div>
                <div class="empty-state-subtext">Create your first bylaw to get started</div>
            </div>
        `;
        return;
    }

    // Sort by number
    const sorted = [...bylaws].sort((a, b) => (a.number || 0) - (b.number || 0));
    
        container.innerHTML = sorted.map(bylaw => renderBylawItem(bylaw)).join('');
    } catch (error) {
        console.error('Error loading bylaws:', error);
        container.innerHTML = `
            <div class="empty-state">
                <div class="empty-state-icon">⚠️</div>
                <div class="empty-state-text">Error loading bylaws</div>
                <div class="empty-state-subtext">${error.message || 'Please try again later'}</div>
            </div>
        `;
    }
}

function renderBylawItem(bylaw) {
    return `
        <div class="bylaw-item" data-id="${bylaw.id}">
            <div class="bylaw-item-header">
                <div class="bylaw-item-title">Bylaw #${bylaw.number || bylaw.bylawNumber || 'N/A'}</div>
                <div class="bylaw-item-actions">
                    <button class="action-btn view" onclick="viewBylaw('${bylaw.id}')" title="View">👁️</button>
                    <button class="action-btn edit" onclick="editBylaw('${bylaw.id}')" title="Edit">✏️</button>
                    <button class="action-btn delete" onclick="deleteBylaw('${bylaw.id}')" title="Delete">🗑️</button>
                </div>
            </div>
            <div class="bylaw-item-content">
                <strong>${bylaw.title || bylaw.bylawTitle || 'Untitled Bylaw'}</strong>
                <p>${(bylaw.content || bylaw.bylawContent || '').substring(0, 150)}...</p>
            </div>
        </div>
    `;
}

function viewBylaw(id) {
    window.location.href = `bylaw-view.html?id=${id}`;
}

function editBylaw(id) {
    window.location.href = `bylaw-form.html?id=${id}`;
}

async function deleteBylaw(id) {
    try {
        let bylaw = null;
        if (typeof asaAPI !== 'undefined') {
            try {
                bylaw = await asaAPI.bylaws.getBylaw(id);
            } catch (e) {
                const bylaws = await getBylawsSync();
                bylaw = bylaws.find(b => b.id === id);
            }
        } else {
            const bylaws = await getBylawsSync();
            bylaw = bylaws.find(b => b.id === id);
        }
        
        const bylawName = bylaw ? (`Bylaw #${bylaw.bylaw_number || bylaw.number || bylaw.bylawNumber || ''} - ${bylaw.bylaw_title || bylaw.title || bylaw.bylawTitle || 'Untitled'}`) : 'this bylaw';
        
        if (confirm(`⚠️ WARNING: Are you sure you want to delete "${bylawName}"?\n\nThis action cannot be undone. The bylaw will be permanently removed from the system.`)) {
            if (typeof asaAPI !== 'undefined') {
                await asaAPI.bylaws.deleteBylaw(id);
            } else {
                const bylaws = await getBylawsSync();
                const filtered = bylaws.filter(b => b.id !== id);
                saveBylaws(filtered);
            }
            await loadBylaws();
            alert('Bylaw deleted successfully.');
        }
    } catch (error) {
        console.error('Error deleting bylaw:', error);
        alert('Error deleting bylaw: ' + (error.message || 'Unknown error'));
    }
}

// ============================================
// Bylaw Form
// ============================================

async function initBylawForm() {
    const form = document.getElementById('bylawForm');
    const urlParams = new URLSearchParams(window.location.search);
    const bylawId = urlParams.get('id');

    if (bylawId) {
        await loadBylawForEdit(bylawId);
    }

    if (form) {
        form.addEventListener('submit', handleBylawSubmit);
    }
}

async function loadBylawForEdit(id) {
    try {
        let bylaw = null;
        if (typeof asaAPI !== 'undefined') {
            const bylawData = await asaAPI.bylaws.getBylaw(id);
            bylaw = {
                id: bylawData.id,
                number: bylawData.bylaw_number || bylawData.number || 0,
                bylawNumber: bylawData.bylaw_number || bylawData.number || 0,
                title: bylawData.bylaw_title || bylawData.title || '',
                bylawTitle: bylawData.bylaw_title || bylawData.title || '',
                content: bylawData.bylaw_content || bylawData.content || '',
                bylawContent: bylawData.bylaw_content || bylawData.content || ''
            };
        } else {
            const bylaws = await getBylawsSync();
            bylaw = bylaws.find(b => b.id === id);
        }
        
        if (bylaw) {
        document.getElementById('formTitle').textContent = 'Update Bylaw';
        document.getElementById('bylawNumber').value = bylaw.number || bylaw.bylawNumber || '';
        document.getElementById('bylawTitle').value = bylaw.title || bylaw.bylawTitle || '';
        document.getElementById('bylawContent').value = bylaw.content || bylaw.bylawContent || '';
        
            document.getElementById('bylawForm').dataset.editId = id;
        }
    } catch (error) {
        console.error('Error loading bylaw for edit:', error);
        alert('Error loading bylaw: ' + (error.message || 'Unknown error'));
    }
}

async function handleBylawSubmit(e) {
    e.preventDefault();
    
    const form = e.target;
    const editId = form.dataset.editId;
    
    const bylawData = {
        bylaw_number: parseInt(document.getElementById('bylawNumber').value),
        bylaw_title: document.getElementById('bylawTitle').value,
        bylaw_content: document.getElementById('bylawContent').value,
        status: 'pending'
    };

    try {
        if (editId && typeof asaAPI !== 'undefined') {
            await asaAPI.bylaws.updateBylaw(editId, bylawData);
        } else if (typeof asaAPI !== 'undefined') {
            await asaAPI.bylaws.createBylaw(bylawData);
        } else {
            // Fallback to localStorage
            const bylaws = await getBylawsSync();
            const fullBylawData = {
                id: editId || generateBylawId(),
                number: bylawData.bylaw_number,
                bylawNumber: bylawData.bylaw_number,
                title: bylawData.bylaw_title,
                bylawTitle: bylawData.bylaw_title,
                content: bylawData.bylaw_content,
                bylawContent: bylawData.bylaw_content,
                status: 'pending',
                createdAt: editId ? bylaws.find(b => b.id === editId)?.createdAt : new Date().toISOString(),
                updatedAt: new Date().toISOString()
            };
            
            if (editId) {
                const index = bylaws.findIndex(b => b.id === editId);
                if (index !== -1) {
                    bylaws[index] = { ...bylaws[index], ...fullBylawData };
                }
            } else {
                bylaws.push(fullBylawData);
            }
            saveBylaws(bylaws);
        }
        
        alert('Bylaw submitted for approval successfully!');
        window.location.href = 'bylaw.html';
    } catch (error) {
        console.error('Error saving bylaw:', error);
        alert('Error saving bylaw: ' + (error.message || 'Unknown error'));
    }
}

function generateBylawId() {
    return 'bylaw_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
}

// ============================================
// Suggestions Management
// ============================================

async function initSuggestionsPage() {
    await loadSuggestions();
}

async function getSuggestionsSync() {
    // Synchronous version for backward compatibility
    const stored = localStorage.getItem(STORAGE_KEYS.SUGGESTIONS);
    return stored ? JSON.parse(stored) : [];
}

async function getSuggestions(filters = {}) {
    if (typeof asaAPI === 'undefined') {
        return await getSuggestionsSync();
    }
    
    try {
        const suggestions = await asaAPI.suggestions.getAllSuggestions(filters);
        // Normalize API response - add viewed field for backward compatibility
        return suggestions.map(s => ({
            id: s.id,
            policyId: s.policy_id,
            suggestion: s.suggestion || '',
            status: s.status || 'pending',
            viewed: s.status === 'viewed' || s.status !== 'pending',
            createdAt: s.created_at,
            updatedAt: s.updated_at
        }));
    } catch (error) {
        console.error('Error fetching suggestions:', error);
        return [];
    }
}

function saveSuggestions(suggestions) {
    localStorage.setItem(STORAGE_KEYS.SUGGESTIONS, JSON.stringify(suggestions));
}

async function loadSuggestions() {
    const container = document.getElementById('suggestionsList');
    if (!container) return;
    
    container.innerHTML = '<div class="loading">Loading suggestions...</div>';
    
    try {
        const suggestions = await getSuggestions();

        if (suggestions.length === 0) {
        container.innerHTML = `
            <div class="empty-state">
                <div class="empty-state-icon">💡</div>
                <div class="empty-state-text">No suggestions found</div>
                <div class="empty-state-subtext">Student suggestions will appear here</div>
            </div>
        `;
        return;
    }

    // Sort by date (newest first)
    const sorted = [...suggestions].sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
    
        container.innerHTML = sorted.map(suggestion => renderSuggestionItem(suggestion)).join('');
    } catch (error) {
        console.error('Error loading suggestions:', error);
        container.innerHTML = `
            <div class="empty-state">
                <div class="empty-state-icon">⚠️</div>
                <div class="empty-state-text">Error loading suggestions</div>
                <div class="empty-state-subtext">${error.message || 'Please try again later'}</div>
            </div>
        `;
    }
}

function renderSuggestionItem(suggestion) {
    const date = new Date(suggestion.createdAt).toLocaleDateString();
    const viewedClass = suggestion.viewed ? '' : 'new';
    
    return `
        <div class="suggestion-item ${viewedClass}" data-id="${suggestion.id}">
            <div class="suggestion-header">
                <div class="suggestion-meta">
                    <div class="suggestion-policy">Policy: ${suggestion.policyReference || 'General'}</div>
                    <div class="suggestion-date">${date}</div>
                </div>
                <div class="suggestion-actions">
                    <button class="btn btn-secondary" onclick="markSuggestionViewed('${suggestion.id}')">Mark as Read</button>
                    <button class="btn btn-secondary" onclick="deleteSuggestion('${suggestion.id}')">Delete</button>
                </div>
            </div>
            <div class="suggestion-content">${suggestion.content || suggestion.suggestion || ''}</div>
        </div>
    `;
}

async function markSuggestionViewed(id) {
    // Note: API doesn't have a "viewed" field, so this is just for local UI state
    // In a real implementation, you might want to track this differently
    try {
        const suggestions = await getSuggestions();
        // This is just for local UI - API doesn't support this field
        await loadSuggestions();
    } catch (error) {
        console.error('Error marking suggestion viewed:', error);
    }
}

async function deleteSuggestion(id) {
    try {
        let suggestion = null;
        if (typeof asaAPI !== 'undefined') {
            try {
                // Get suggestion preview (API doesn't return single suggestion, but we can get all and find)
                const suggestions = await getSuggestions();
                suggestion = suggestions.find(s => s.id === id);
            } catch (e) {
                const suggestions = await getSuggestionsSync();
                suggestion = suggestions.find(s => s.id === id);
            }
        } else {
            const suggestions = await getSuggestionsSync();
            suggestion = suggestions.find(s => s.id === id);
        }
        
        const suggestionPreview = suggestion ? (suggestion.content || suggestion.suggestion || '').substring(0, 50) : 'this suggestion';
        
        if (confirm(`⚠️ WARNING: Are you sure you want to delete this student suggestion?\n\nPreview: "${suggestionPreview}..."\n\nThis action cannot be undone. The suggestion will be permanently removed from the system.`)) {
            if (typeof asaAPI !== 'undefined') {
                await asaAPI.suggestions.deleteSuggestion(id);
            } else {
                const suggestions = await getSuggestionsSync();
                const filtered = suggestions.filter(s => s.id !== id);
                saveSuggestions(filtered);
            }
            await loadSuggestions();
            alert('Suggestion deleted successfully.');
        }
    } catch (error) {
        console.error('Error deleting suggestion:', error);
        alert('Error deleting suggestion: ' + (error.message || 'Unknown error'));
    }
}

// ============================================
// Common Functionality
// ============================================

function initSearch() {
    const searchInput = document.getElementById('searchInput');
    if (searchInput) {
        searchInput.addEventListener('input', handleSearch);
    }
}

function handleSearch(e) {
    const query = e.target.value.toLowerCase();
    const currentPage = getCurrentPage();
    
    if (currentPage === 'policies') {
        filterPolicies(query);
    } else if (currentPage === 'bylaw') {
        filterBylaws(query);
    } else if (currentPage === 'suggestions-manage') {
        filterSuggestions(query);
    }
}

function filterPolicies(query) {
    const items = document.querySelectorAll('.policy-item');
    items.forEach(item => {
        const text = item.textContent.toLowerCase();
        item.style.display = text.includes(query) ? 'block' : 'none';
    });
}

function filterBylaws(query) {
    const items = document.querySelectorAll('.bylaw-item');
    items.forEach(item => {
        const text = item.textContent.toLowerCase();
        item.style.display = text.includes(query) ? 'block' : 'none';
    });
}

function filterSuggestions(query) {
    const items = document.querySelectorAll('.suggestion-item');
    items.forEach(item => {
        const text = item.textContent.toLowerCase();
        item.style.display = text.includes(query) ? 'block' : 'none';
    });
}

function initSidebarNavigation() {
    // Highlight active nav item based on current page
    const currentPage = getCurrentPage();
    const navItems = document.querySelectorAll('.nav-item');
    
    navItems.forEach(item => {
        item.classList.remove('active');
        const href = item.getAttribute('href');
        if (href && href.includes(currentPage)) {
            item.classList.add('active');
        }
    });
}

// ============================================
// Approval Workflow (for future implementation)
// ============================================

async function approvePolicy(id, showAlert = true) {
    try {
        if (typeof asaAPI !== 'undefined') {
            await asaAPI.policies.approvePolicy(id);
        } else {
            // Fallback to localStorage
            const policies = await getPoliciesSync();
            const index = policies.findIndex(p => p.id === id);
            if (index !== -1) {
                policies[index].status = 'approved';
                policies[index].approvedAt = new Date().toISOString();
                savePolicies(policies);
            }
        }
        
        // Only reload and show alert if not called from approvals page
        if (showAlert) {
            await loadPolicies();
            alert('Policy approved successfully!');
        }
    } catch (error) {
        console.error('Error approving policy:', error);
        if (showAlert) {
            alert('Error approving policy: ' + (error.message || 'Unknown error'));
        }
    }
}

async function approveBylaw(id, showAlert = true) {
    try {
        if (typeof asaAPI !== 'undefined') {
            await asaAPI.bylaws.approveBylaw(id);
        } else {
            // Fallback to localStorage
            const bylaws = await getBylawsSync();
            const index = bylaws.findIndex(b => b.id === id);
            if (index !== -1) {
                bylaws[index].status = 'approved';
                bylaws[index].approvedAt = new Date().toISOString();
                saveBylaws(bylaws);
            }
        }
        
        // Only reload and show alert if not called from approvals page
        if (showAlert) {
            await loadBylaws();
            alert('Bylaw approved successfully!');
        }
    } catch (error) {
        console.error('Error approving bylaw:', error);
        if (showAlert) {
            alert('Error approving bylaw: ' + (error.message || 'Unknown error'));
        }
    }
}

// Review functions
function getReviews() {
    const stored = localStorage.getItem(STORAGE_KEYS.REVIEWS);
    return stored ? JSON.parse(stored) : [];
}

function saveReviews(reviews) {
    localStorage.setItem(STORAGE_KEYS.REVIEWS, JSON.stringify(reviews));
}

// ============================================
// Admin Members Management
// ============================================

function getAdminMembers() {
    const stored = localStorage.getItem(STORAGE_KEYS.ADMIN_MEMBERS);
    return stored ? JSON.parse(stored) : [];
}

function saveAdminMembers(members) {
    localStorage.setItem(STORAGE_KEYS.ADMIN_MEMBERS, JSON.stringify(members));
}

function addAdminMember(memberData) {
    const members = getAdminMembers();
    
    // Check if email already exists
    if (members.some(m => m.email.toLowerCase() === memberData.email.toLowerCase())) {
        alert('An admin member with this email already exists.');
        return false;
    }
    
    const newMember = {
        id: 'admin_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9),
        firstName: memberData.firstName,
        lastName: memberData.lastName,
        email: memberData.email.toLowerCase(),
        password: memberData.password,
        createdAt: new Date().toISOString()
    };
    
    members.push(newMember);
    saveAdminMembers(members);
    alert('Admin member added successfully!');
    return true;
}

function updateAdminMember(id, memberData) {
    const members = getAdminMembers();
    const index = members.findIndex(m => m.id === id);
    
    if (index === -1) {
        alert('Member not found.');
        return false;
    }
    
    // Check if email already exists for another member
    const emailExists = members.some(m => 
        m.id !== id && m.email.toLowerCase() === memberData.email.toLowerCase()
    );
    
    if (emailExists) {
        alert('An admin member with this email already exists.');
        return false;
    }
    
    members[index] = {
        ...members[index],
        firstName: memberData.firstName,
        lastName: memberData.lastName,
        email: memberData.email.toLowerCase(),
        password: memberData.password,
        updatedAt: new Date().toISOString()
    };
    
    saveAdminMembers(members);
    alert('Admin member updated successfully!');
    return true;
}

// Export functions for global access
window.viewPolicy = viewPolicy;
window.editPolicy = editPolicy;
window.deletePolicy = deletePolicy;
window.toggleSection = toggleSection;
window.viewBylaw = viewBylaw;
window.editBylaw = editBylaw;
window.deleteBylaw = deleteBylaw;
window.markSuggestionViewed = markSuggestionViewed;
window.deleteSuggestion = deleteSuggestion;
window.approvePolicy = approvePolicy;
window.approveBylaw = approveBylaw;
window.getPolicies = getPolicies;
window.getReviews = getReviews;
window.getSectionName = getSectionName;
window.getAdminMembers = getAdminMembers;
window.saveAdminMembers = saveAdminMembers;
window.addAdminMember = addAdminMember;
window.updateAdminMember = updateAdminMember;
window.toggleProfilePanel = toggleProfilePanel;
window.closeProfilePanel = closeProfilePanel;
window.handleLogout = handleLogout;

